### ISSUE TITLE
QGIS Server version

### ISSUE THREAD

**Issue by NyakudyaA** [g3w-suite/g3w-suite-docker#1]
# Problem

I am trying to set up this demo service and all work well with the default images. I, however, run into errors when I try to change the `qgis-server` images.

I tried the following and it doesn't startup

```
version: '2.2'
services:

 

  qgisserver:
    restart: unless-stopped
    image: 3liz/qgis-map-server:3.10
    #hostname: qgis-server
    container_name: qgisserver4${COMPOSE_PROJECT_NAME}
    environment:
      - QGSRV_SERVER_WORKERS=6
      - QGSRV_LOGGING_LEVEL=DEBUG
      - QGSRV_CACHE_ROOTDIR=/djangoassets/geodata
      - QGSRV_CACHE_SIZE=100
      - QGSRV_SERVER_TIMEOUT=300
    volumes_from:
      - django

  
```

The main problem is that this QGIS server runs on port 8080 inside docker and the URL for qgis server should not be hardcoded with the path ie `&map=/djangoassets/geodata` but it should be relative to the `QGSRV_CACHE_ROOTDIR` so the request should be like `&map=test.qgis` or 
`&map=/folder/test.qgis` assuming `folder` is a directory inside /djangoassets/geodata

Otherwise thanks awesome work.
