### ISSUE TITLE
Changing port in docker compose is not enough to have it work in restricted environment

### ISSUE THREAD

**Issue by moovida** [g3w-suite/g3w-suite-docker#124]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-suite-docker/issues) and this bug has never been reported before

### Subject of the issue

If you want to run the docker compose on port 80, changing the port in the compose yml works only partially. 

### Steps to reproduce

1. edit the docker-compose.yml and change the nginx part from

```
  nginx:
    image: nginx
    ports:
      - "8080:8080"
```
to
```
  nginx:
    image: nginx
    ports:
      - "80:8080"
```

2. run the suite in an environment in which port 8080 is blocked
3. load a project and ho on the project's map page

You should experience a timeout due to the fact that there is a call going to something like:
```
http://yourhost:8080/api/config/1/qdjango/1?_t=1725437423.358987
```

### Environment

- g3w-admin: 3.8.x
